import React, { createContext, useContext, useState, useEffect } from "react";

type Lang = "en" | "ar";

const T = {
  en: {
    home: "Home",
    menu: "Menu",
    myOrders: "My Orders",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    orderNow: "Order Now",
    viewMenu: "View Menu",
    fullMenu: "Full Menu",
    seeAll: "See All",
    addToCart: "Add",
    added: "Added",
    addedToCart: "Added to Cart",
    proceedToCheckout: "Proceed to Checkout",
    placeOrder: "Place Order",
    browseMenu: "Browse Menu",
    yourCart: "Your Cart",
    cartEmpty: "Your cart is empty",
    cartEmptySub: "Add items from the menu to get started",
    subtotal: "Subtotal",
    delivery: "Delivery",
    discount: "Discount",
    total: "Total",
    promoCode: "Promo code",
    apply: "Apply",
    ourMenu: "Our Menu",
    freshFromSea: "Fresh from the sea, prepared with love",
    searchDishes: "Search dishes...",
    vegetarian: "Vegetarian",
    allItems: "All Items",
    bestSeller: "Best Seller",
    spicy: "Spicy",
    veg: "Veg",
    chefsPickSub: "Handpicked favorites from our kitchen",
    chefsPick: "Chef's Picks",
    featured: "Featured",
    howItWorks: "How It Works",
    simpleProcess: "Simple Process",
    freshFoodAtDoor: "Fresh food at your door in three easy steps",
    ourBranches: "Our Branches",
    locations: "Locations",
    findNearest: "Find the branch nearest to you",
    detectLocation: "Detect My Location",
    detecting: "Detecting...",
    orderFromBranch: "Order from this branch",
    nearestBranch: "Nearest Branch",
    viewOnMaps: "View on Maps",
    mobileApp: "Mobile App",
    orderAnywhere: "Order anytime, anywhere",
    mobileAppSub: "Download the Sea Gull app for even smoother experience with real-time tracking and exclusive offers.",
    appStore: "App Store",
    googlePlay: "Google Play",
    testimonials: "Testimonials",
    whatCustomersSay: "What our customers say",
    readyToExperience: "Ready to experience Sea Gull?",
    ctaSub: "Join over 10,000 satisfied customers. Fresh seafood delivered to your door.",
    signInBack: "Welcome back",
    signInSub: "Sign in to your Sea Gull account",
    createAccount: "Create account",
    createAccountSub: "Join Sea Gull restaurant",
    fullName: "Full Name",
    yourFullName: "Your full name",
    phoneNumber: "Phone Number",
    password: "Password",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    orderPlaced: "Order Placed!",
    orderPlacedSub: "Your order has been received.",
    estimatedDelivery: "Estimated delivery: 25–40 minutes",
    trackMyOrder: "Track My Order",
    orderAgain: "Order Again",
    deliveryAddress: "Delivery Address",
    whereDeliver: "Where should we deliver?",
    streetAddress: "Street Address",
    streetPlaceholder: "123 Nile Street, Apt 4B",
    cityArea: "City / Area",
    cityPlaceholder: "Fifth Settlement, New Cairo",
    deliveryNotes: "Delivery Notes (optional)",
    notesPlaceholder: "Ring bell twice, leave at door...",
    selectBranch: "Select nearest branch",
    paymentMethod: "Payment Method",
    cashOnDelivery: "Cash on Delivery",
    cashOnDeliverySub: "Pay when your order arrives",
    visaCard: "Visa / Credit Card",
    visaCardSub: "Pay securely online",
    orderSummary: "Order Summary",
    orderingAs: "Ordering as",
    myOrdersTitle: "My Orders",
    ordersTotal: "orders total",
    noOrdersYet: "No orders yet",
    noOrdersYetSub: "Start your first seafood adventure!",
    signInToOrders: "Sign in to view orders",
    signInToOrdersSub: "Track your order history and current deliveries",
    orderProgress: "Order Progress",
    items: "Items",
    deliveryInfo: "Delivery Info",
    address: "Address",
    branch: "Branch",
    payment: "Payment",
    rider: "Rider",
    backToOrders: "My Orders",
    viewAll: "View All",
    preparationTime: "Prep time",
    calories: "cal",
    chooseSize: "Choose Size",
    addOns: "Add-Ons",
    quantity: "Quantity",
    close: "Close",
    loading: "Loading...",
    reviews: "Reviews",
    ratings: "ratings",
    noItemsFound: "No dishes found",
    noItemsFoundSub: "Try a different category or search term",
    back: "Back",
    checkout: "Checkout",
    statistics: "Statistics",
    rating: "Average Rating",
    deliveryTime: "Delivery Time",
    branches: "Across Cairo",
    happyCustomers: "Happy Customers",
    browseByCategory: "Browse by Category",
    whatCraving: "What are you craving?",
    openNow: "Open Now",
    hours: "Hours",
    phoneLabel: "Phone",
    realTimeTracking: "Real-time tracking",
    loyaltyPoints: "Loyalty points",
    exclusiveDeals: "Exclusive deals",
    easyReordering: "Easy reordering",
    privacy: "Privacy",
    terms: "Terms",
    cookies: "Cookies",
    allRightsReserved: "All rights reserved.",
    tagline: "Premium seafood experience since 2010. Freshly caught, expertly prepared, and delivered to your door.",
  },
  ar: {
    home: "الرئيسية",
    menu: "القائمة",
    myOrders: "طلباتي",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    signOut: "تسجيل الخروج",
    orderNow: "اطلب الآن",
    viewMenu: "عرض القائمة",
    fullMenu: "القائمة الكاملة",
    seeAll: "عرض الكل",
    addToCart: "إضافة",
    added: "أُضيف",
    addedToCart: "أُضيف للسلة",
    proceedToCheckout: "إتمام الطلب",
    placeOrder: "تأكيد الطلب",
    browseMenu: "تصفح القائمة",
    yourCart: "سلة التسوق",
    cartEmpty: "السلة فارغة",
    cartEmptySub: "أضف أصنافاً من القائمة للبدء",
    subtotal: "المجموع الفرعي",
    delivery: "رسوم التوصيل",
    discount: "خصم",
    total: "الإجمالي",
    promoCode: "كود الخصم",
    apply: "تطبيق",
    ourMenu: "قائمتنا",
    freshFromSea: "طازج من البحر، محضّر بمحبة",
    searchDishes: "ابحث عن أطباق...",
    vegetarian: "نباتي",
    allItems: "جميع الأصناف",
    bestSeller: "الأكثر مبيعاً",
    spicy: "حار",
    veg: "نباتي",
    chefsPickSub: "أبرز ما يختاره الشيف من مطبخنا",
    chefsPick: "اختيارات الشيف",
    featured: "مميز",
    howItWorks: "كيف يعمل",
    simpleProcess: "عملية بسيطة",
    freshFoodAtDoor: "طعام طازج على بابك في ثلاث خطوات",
    ourBranches: "فروعنا",
    locations: "المواقع",
    findNearest: "ابحث عن أقرب فرع إليك",
    detectLocation: "تحديد موقعي",
    detecting: "جارٍ التحديد...",
    orderFromBranch: "اطلب من هذا الفرع",
    nearestBranch: "أقرب فرع",
    viewOnMaps: "عرض على الخريطة",
    mobileApp: "التطبيق",
    orderAnywhere: "اطلب في أي وقت وأي مكان",
    mobileAppSub: "حمّل تطبيق نورس لتجربة أسهل مع تتبع الطلب الفوري وعروض حصرية.",
    appStore: "App Store",
    googlePlay: "Google Play",
    testimonials: "آراء عملائنا",
    whatCustomersSay: "ماذا يقول عملاؤنا",
    readyToExperience: "جاهز لتجربة نورس؟",
    ctaSub: "انضم لأكثر من 10,000 عميل سعيد. مأكولات بحرية طازجة تُوصَّل لبابك.",
    signInBack: "مرحباً بعودتك",
    signInSub: "سجّل دخولك إلى حساب نورس",
    createAccount: "إنشاء حساب",
    createAccountSub: "انضم إلى مطعم نورس",
    fullName: "الاسم الكامل",
    yourFullName: "اسمك الكامل",
    phoneNumber: "رقم الهاتف",
    password: "كلمة المرور",
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    orderPlaced: "تم تأكيد الطلب!",
    orderPlacedSub: "تم استلام طلبك.",
    estimatedDelivery: "الوقت التقديري: 25–40 دقيقة",
    trackMyOrder: "تتبع طلبي",
    orderAgain: "اطلب مجدداً",
    deliveryAddress: "عنوان التوصيل",
    whereDeliver: "أين نوصّل لك؟",
    streetAddress: "العنوان *",
    streetPlaceholder: "مثال: شارع النيل، شقة 4B",
    cityArea: "المدينة / المنطقة",
    cityPlaceholder: "التجمع الخامس، القاهرة الجديدة",
    deliveryNotes: "ملاحظات التوصيل (اختياري)",
    notesPlaceholder: "اضغط الجرس مرتين، اتركه عند الباب...",
    selectBranch: "اختر أقرب فرع",
    paymentMethod: "طريقة الدفع",
    cashOnDelivery: "الدفع عند الاستلام",
    cashOnDeliverySub: "ادفع عند وصول طلبك",
    visaCard: "فيزا / بطاقة ائتمانية",
    visaCardSub: "ادفع بأمان عبر الإنترنت",
    orderSummary: "ملخص الطلب",
    orderingAs: "الطلب باسم",
    myOrdersTitle: "طلباتي",
    ordersTotal: "طلب بالمجموع",
    noOrdersYet: "لا طلبات بعد",
    noOrdersYetSub: "ابدأ مغامرتك البحرية الأولى!",
    signInToOrders: "سجّل دخولك لعرض الطلبات",
    signInToOrdersSub: "تتبع سجل طلباتك والتوصيلات الجارية",
    orderProgress: "تقدم الطلب",
    items: "الأصناف",
    deliveryInfo: "معلومات التوصيل",
    address: "العنوان",
    branch: "الفرع",
    payment: "الدفع",
    rider: "المندوب",
    backToOrders: "طلباتي",
    viewAll: "عرض الكل",
    preparationTime: "وقت التحضير",
    calories: "سعرة",
    chooseSize: "اختر الحجم",
    addOns: "الإضافات",
    quantity: "الكمية",
    close: "إغلاق",
    loading: "جارٍ التحميل...",
    reviews: "تقييمات",
    ratings: "تقييم",
    noItemsFound: "لا أطباق متاحة",
    noItemsFoundSub: "جرّب فئة أخرى أو مصطلح بحث مختلف",
    back: "رجوع",
    checkout: "الدفع",
    statistics: "إحصاءات",
    rating: "متوسط التقييم",
    deliveryTime: "وقت التوصيل",
    branches: "عبر القاهرة",
    happyCustomers: "عميل سعيد",
    browseByCategory: "تصفح حسب الفئة",
    whatCraving: "ماذا تشتهي؟",
    openNow: "مفتوح الآن",
    hours: "مواعيد العمل",
    phoneLabel: "الهاتف",
    realTimeTracking: "تتبع فوري",
    loyaltyPoints: "نقاط ولاء",
    exclusiveDeals: "عروض حصرية",
    easyReordering: "إعادة طلب سهلة",
    privacy: "الخصوصية",
    terms: "الشروط",
    cookies: "ملفات تعريف الارتباط",
    allRightsReserved: "جميع الحقوق محفوظة.",
    tagline: "تجربة مأكولات بحرية فاخرة منذ 2010. طازج ومحضّر باحتراف، يصلك على بابك.",
  },
};

interface LangCtx {
  lang: Lang;
  toggleLang: () => void;
  t: (key: keyof typeof T["en"]) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LangCtx>({
  lang: "en",
  toggleLang: () => {},
  t: (k) => T.en[k],
  isRTL: false,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("sg-lang") as Lang) ?? "en");

  useEffect(() => {
    const dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
    localStorage.setItem("sg-lang", lang);
  }, [lang]);

  const toggleLang = () => setLang((l) => (l === "en" ? "ar" : "en"));
  const t = (key: keyof typeof T["en"]): string => T[lang][key] ?? T.en[key];
  const isRTL = lang === "ar";

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
