const palette = {
  navyDeep: "#0A1628",
  navyDark: "#0D1F3C",
  navyMid: "#122848",
  oceanBlue: "#1A6FA8",
  oceanLight: "#2196CC",
  aqua: "#0FBCD4",
  silver: "#B8C8D8",
  silverLight: "#D4E4F0",
  charcoal: "#2C3E50",
  white: "#FFFFFF",
  offWhite: "#F4F8FC",
  gold: "#D4AF37",
  goldLight: "#F0CC60",
  coral: "#E8604C",
  green: "#27AE60",
  textMuted: "#7A9BB8",
};

export const Colors = {
  light: {
    background: palette.offWhite,
    backgroundSecondary: palette.white,
    surface: palette.white,
    surfaceSecondary: "#EBF2F9",
    text: palette.navyDeep,
    textSecondary: palette.charcoal,
    textMuted: palette.textMuted,
    primary: palette.oceanBlue,
    primaryDark: palette.navyDeep,
    primaryLight: palette.oceanLight,
    accent: palette.aqua,
    gold: palette.gold,
    goldLight: palette.goldLight,
    error: palette.coral,
    success: palette.green,
    silver: palette.silver,
    silverLight: palette.silverLight,
    border: "#D4E4F0",
    borderLight: "#EBF2F9",
    tint: palette.oceanBlue,
    tabIconDefault: palette.textMuted,
    tabIconSelected: palette.oceanBlue,
    headerBackground: palette.navyDeep,
    navyMid: palette.navyMid,
    white: palette.white,
    cardShadow: "rgba(10, 22, 40, 0.12)",
    overlay: "rgba(10, 22, 40, 0.6)",
    gradientStart: palette.navyDeep,
    gradientEnd: palette.oceanBlue,
    navyDeep: palette.navyDeep,
    oceanBlue: palette.oceanBlue,
    aqua: palette.aqua,
  },
  dark: {
    background: palette.navyDeep,
    backgroundSecondary: palette.navyDark,
    surface: palette.navyMid,
    surfaceSecondary: "#162035",
    text: palette.white,
    textSecondary: palette.silverLight,
    textMuted: palette.silver,
    primary: palette.oceanLight,
    primaryDark: palette.navyDeep,
    primaryLight: palette.aqua,
    accent: palette.aqua,
    gold: palette.goldLight,
    goldLight: palette.goldLight,
    error: palette.coral,
    success: palette.green,
    silver: palette.silver,
    silverLight: palette.silverLight,
    border: "#1E3050",
    borderLight: "#1A2A44",
    tint: palette.oceanLight,
    tabIconDefault: palette.textMuted,
    tabIconSelected: palette.aqua,
    headerBackground: palette.navyDeep,
    navyMid: palette.navyMid,
    white: palette.white,
    cardShadow: "rgba(0, 0, 0, 0.4)",
    overlay: "rgba(0, 0, 0, 0.7)",
    gradientStart: "#060E1A",
    gradientEnd: palette.navyMid,
    navyDeep: palette.navyDeep,
    oceanBlue: palette.oceanLight,
    aqua: palette.aqua,
  },
};

export default Colors;
